Declaring Tensors

In [1]:
import tensorflow as tf

In [2]:
row_dim = 2 
col_dim = 2
rd =3
cd =3

In [3]:
zeros_tensor = tf.zeros([row_dim, col_dim])

In [6]:
zeros_tensor

<tf.Tensor 'zeros:0' shape=(2, 2) dtype=float32>

In [3]:
ones_tensor = tf.ones([row_dim, col_dim])

In [4]:
ones_tensor

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [7]:
filled_tensor = tf.fill([rd,cd],15)

In [8]:
filled_tensor

<tf.Tensor 'Fill:0' shape=(3, 3) dtype=int32>

In [9]:
zeros_sim = tf.zeros_like(filled_tensor)

In [10]:
zeros_sim

<tf.Tensor 'zeros_like:0' shape=(3, 3) dtype=int32>

In [18]:
#sequence tensor
linear_tensor = tf.linspace(start = 0.0, stop =11, num = 10, name = None)

In [19]:
linear_tensor

<tf.Tensor 'LinSpace_5:0' shape=(10,) dtype=float32>

In [20]:
integer_tensor = tf.range(6,15,3)

In [21]:
integer_tensor

<tf.Tensor 'range:0' shape=(3,) dtype=int32>

In [22]:
print(integer_tensor)

Tensor("range:0", shape=(3,), dtype=int32)


In [34]:
#random tensor
ran_tsr = tf.random_uniform([cd,rd],minval =0, maxval = 3, dtype = tf.float32)#for uniform distribution 

In [35]:
ran_tsr

<tf.Tensor 'random_uniform_3:0' shape=(3, 3) dtype=float32>

In [6]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

In [9]:
import numpy as np
sess = tf.Session()
x = tf.placeholder(tf.float32, shape = [2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict = {x:x_vals})

array([[ 0.35189682,  0.54673982],
       [ 0.26329461,  0.55595595]], dtype=float32)

In [10]:
#Working with matrix

In [12]:
#create new matrix
identity_matrix = tf.diag([1.0,1.0 ,1.0])

In [13]:
identity_matrix

<tf.Tensor 'Diag:0' shape=(3, 3) dtype=float32>

In [14]:
A = tf.truncated_normal([2,3])
B = tf.fill([2,3], 10)

In [15]:
B

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

In [16]:
sess.run(identity_matrix)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [17]:
sess.run(A)

array([[ 0.54135948, -0.41412979,  1.46573472],
       [ 0.65189457,  0.62048227, -0.66952378]], dtype=float32)

In [18]:
sess.run(B)

array([[10, 10, 10],
       [10, 10, 10]])

In [4]:
sess = tf.Session()

In [5]:
sess.run(tf.nn.relu([-5,5,2])) #relu(z) = max(0,z)

array([0, 5, 2])

In [7]:
sess.run(tf.nn.sigmoid([-3.0,3.0,0])) #sigmoid(x) = 1/(1 + exp(-x))

array([ 0.04742587,  0.95257413,  0.5       ], dtype=float32)

In [8]:
#tan hypebolic tanh(x) = (exp(x) - exp(-x)) /(exp(x) + exp(-x))
sess.run(tf.nn.tanh([-1.0, 0.0, 1.0]))

array([-0.76159418,  0.        ,  0.76159418], dtype=float32)

Load the data

In [2]:
#spam ham text data
import requests
import io
from zipfile import ZipFile

In [3]:
zip_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip'

In [4]:
r = requests.get(zip_url)
z = ZipFile(io.BytesIO(r.content))

In [7]:
file = z.read('SMSSpamCollection')
text_data = file.decode()
text_data = text_data.encode('ascii', errors = 'ignore')
text_data = text_data.decode().split('\n')
text_data = [x.split('\t') for x in text_data if len(x)>=1]
[text_data_target, text_data_train] = [list(x) for x in zip(*text_data)]

In [8]:
print(len(text_data_train))

5574


In [9]:
set(text_data_target)

{'ham', 'spam'}

In [10]:
text_data_train[5]

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, 1.50 to rcv"

In [9]:
# The Works of Shakespeare Data
import requests

shakespeare_url = 'http://www.gutenberg.org/cache/epub/100/pg100.txt'
# Get Shakespeare text
response = requests.get(shakespeare_url)
shakespeare_file = response.content
# Decode binary into string
shakespeare_text = shakespeare_file.decode('utf-8')
# Drop first few descriptive paragraphs.
shakespeare_text = shakespeare_text[7675:]
len(shakespeare_text)

5582212